app/urls.py
from django.contrib import admin
from django.urls import path
from companions.views import ( login_view, register_view, logout_view, home_view, special_view)
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home_view, name='home'), 
    path('admin/', admin.site.urls),
    path('password-reset/', 
        auth_views.PasswordResetView.as_view(
            template_name="companions/password_reset.html"
            ), 
        name="password_reset"),
    path('password-reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name="companions/password_reset_done.html"
        ), 
        name="password_reset_done"),
     path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name="companions/password_reset_confirm.html"
        ), 
        name="password_reset_confirm"),
    path('password-reset-complete/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name="companions/password_reset_complete.html"
            ), 
        name="password_reset_complete"),
    path('companions/', include('companions.urls')),
    path('logout/', logout_view, name='logout'),
    path('special/', special_view, name='special')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companions/urls.py
from django.conf.urls import url
from django.urls import path
from companions import views

app_name = 'companions'

urlpatterns = [
    url('register', views.register_view, name='register'),
    url('user_login', views.login_view, name='user_login'),
    url('top10companions', views.companions, name='top10companions'),
    url('jannatulFirdous', views.jannatulFirdous, name="jannatulFirdous"),
    url('first_companion', views.first_companion, name="first_companion"),
    url('second_companion', views.second_companion, name="second_companion"),
    url('third_companion', views.third_companion, name="third_companion"),
    url('fourth_companion', views.fourth_companion, name="fourth_companion"),
    url('fifth_companion', views.fifth_companion, name="fifth_companion"),
    url('sixth_companion', views.sixth_companion, name="sixth_companion"),
    url('seventh_companion', views.seventh_companion, name="seventh_companion"),
    url('eighth_companion', views.eighth_companion, name="eighth_companion"),
    url('ninth_companion', views.ninth_companion, name="ninth_companion"),
    url('tenth_companion', views.tenth_companion, name="tenth_companion"),
]

companions/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.
class UserProfileModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.URLField(blank=True)
    date_of_birth = models.DateField(blank=False)
    def __str__(self):
        return self.user.username

companions/forms.py
from django import forms
from datetime import datetime
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from .models import UserProfileModel
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
    #specify date from 1960 to 2019
NUM_YEARS = [x for x in range(1960, 2019)]

class UserLogin(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')
class UserProfile(forms.ModelForm):
    class Meta():
        model = UserProfileModel
        fields = ('profile_picture', 'date_of_birth')

companions/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse, Http404, QueryDict, HttpResponseRedirect
from django.db import IntegrityError
from django.contrib.auth import (authenticate, get_user_model, login, logout,)
from .forms import UserLogin, UserProfile
from .models import UserProfileModel, User
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
# Create your views here.
    #home page
@login_required
def special_view(request):
    return HttpResponse("You have successfully logged in!")
@csrf_exempt
def home_view(request):  
    return render(request, "companions/index.html")
    #login view
@csrf_exempt
def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("You were inactive")
        else:
            print("your login attempt has failed")
    else:
        return render(request, 'companions/components/login.html', {})
    #logout view
@csrf_exempt
@login_required
def logout_view(request):
    logout(request)
    title = "Logout"
    #redirects to home page
    return redirect("/")
    return render(request, "companions/form.html", {"title": title})
@login_required
def companions(request):
    return render(request, "companions/top10companions.html")
@login_required
def jannatulFirdous(request):
    return render(request, "companions/top6.html")
def register_view(request):
    register = False
    if request.method == 'POST':
        user_form = UserLogin(data=request.POST)
        profile = UserProfile(data=request.POST)
        if user_form.is_valid() and profile.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            user_fprofule = profile.save(commit = False)
            user_fprofule = user
            if 'profile_picture' in request.FILES:
                print("YES")
                user_fprofule.profile_picture = request.FILES['profile_picture']
            user_fprofule.save()
            register = True
        else:
            print(user_form.errors, profile.errors)
    else:
        user_form = UserLogin()
        profile = UserProfile()
    return render(request, 'companions/components/register.html', {'user_form': user_form, 'profile':profile, 'registered':register})
def first_companion(request):
    return render(request, 'companions/AbuBakr.html')
def second_companion(request):
    return render(request, 'companions/Umar.html')
def third_companion(request):
    return render(request, 'companions/Uthman.html')
def fourth_companion(request):
    return render(request, 'companions/Ali.html')
def fifth_companion(request):
    return render(request, 'companions/Talhah.html')
def sixth_companion(request):
    return render(request, 'companions/Zubayr.html')
def seventh_companion(request):
    return render(request, 'companions/AbdurRahman.html')
def eighth_companion(request):
    return render(request, 'companions/Saad.html')
def ninth_companion(request):
    return render(request, 'companions/Said.html')
def tenth_companion(request):
    return render(request, 'companions/AbuUbaidah.html') 

companions/templates/companions/AbdurRahman.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/AbuBakr.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/AbuUbaidah.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/Ali.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/Saad.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/Said.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/Talhah.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/Umar.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/Uthman.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/Zubayr.html
{% extends 'companions/base.html' %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    
  </div>
</div>
{% endblock %}

companions/templates/companions/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'companions/style.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>  
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'home' %}">JTOJ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'companions:register' %}">Register <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'companions:top10companions' %}">The top 10 companions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'companions:jannatulFirdous' %}">How to get to Jannah-Al-Firdous</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'companions:user_login' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav> -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">JTOJ</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'companions:register' %}">Register <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'companions:top10companions' %}">The top 10 companions</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'companions:jannatulFirdous' %}">How to get to Jannah-Al-Firdous</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'companions:user_login' %}">Login</a>
        </li>
        {% endif %}
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>
</body>
</html>

companions/templates/companions/components/login.html
{% extends 'companions/base.html' %}
{% block body_block %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'companions/login.css' %}" />
<div class="container">
    <form method="post" action="{% url 'companions:user_login' %}">
        {% csrf_token %}
        <!-- <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Username"><br/>
        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Password"><br/>
        <input type="submit" name="" value="Login">
        <small class="text-muted ml-2">
            <a href="{% url 'password_reset' %}"> Forgot Your Password? </a>
        </small>   -->
        <div class="row">
          <div class="col-lg-3 col-md-2"></div>
          <div class="col-lg-6 col-md-8 login-box">
              <div class="col-lg-12 login-key">
                  <i class="fa fa-key" aria-hidden="true"></i>
              </div>
              <div class="col-lg-12 login-title">
                  Login
              </div>
    
              <div class="col-lg-12 login-form">
                  <div class="col-lg-12 login-form">
                      <form>
                          <div class="form-group">
                              <label class="form-control-label">USERNAME</label>
                              <input type="text" class="form-control">
                          </div>
                          <div class="form-group">
                              <label class="form-control-label">PASSWORD</label>
                              <input type="password" class="form-control" i>
                          </div>
    
                          <div class="col-lg-12 loginbttm">
                              <div class="col-lg-6 login-btm login-text">
                                  <!-- Error Message -->
                              </div>
                              <div class="col-lg-6 login-btm login-button">
                                  <button type="submit" class="btn btn-outline-primary">LOGIN</button>
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
              <div class="col-lg-3 col-md-2"></div>
          </div>
    </form>
</div>
{% endblock %}

companions/templates/companions/components/password_reset.html
{% extends 'companions/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Change your password</h1>
    <form role="form" action="" method="POST">
        {% csrf_token %}
        <br><br>
          {{form|crispy}}
        <button type="submit" class="btn btn-success"> Reset My Password </button>
    </form>
  </div>
</div>
{% endblock %}

companions/templates/companions/components/password_reset_complete.html
{% extends 'companions/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <div class="alert alert-info">
        Your password was successfully updated, You can sign In again if you'd like!
    </div>
    <a href="{% url 'companions:user_login' %}"> You can now Login :)! </a>
  </div>
</div>
{% endblock %}

companions/templates/companions/components/password_reset_confirm.html
{% extends 'companions/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <form method="post">
      {% csrf_token %}
      <h1 style="text-shadow: 1px 1px 30px #44804d; padding: 10px;"> Change your password below! </h1>
      <br><br>
      {{form|crispy}}
      <button type="submit" class="btn btn-success"> Reset My Password </button>
    </form>
  </div>
</div>
{% endblock %}

companions/templates/companions/components/password_reset_done.html
{% extends 'companions/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <div class="alert alert-info">
        You should receive an email right now!! ;) <br />
        Just follow the instructions sent to you in the email!
    </div>
  </div>
</div>
{% endblock %}

companions/templates/companions/components/register.html
{% extends "companions/base.html" %}
{% load static %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>All of your details have been saved, thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile.as_p }}
          <input type="submit" name="" value="Register">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

companions/templates/companions/index.html
{% extends "companions/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1 style="text-align:center;">Welcome to your Journey to Jannah!</h1>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
    {% else %}
        <h2 style="text-align:center;">Please Register or Login</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

companions/templates/companions/top10companions.html
{% extends 'companions/base.html' %}
{% block body_block %}
{% load staticfiles %}
<div class="container">
  <div class="jumbotron">
    <h4 className="TextCentre" >Heres a list of the top 10 companions that were promised Jannah</h4>
    <div class="container">
      <div class="row">
        <div class="col">
          <a href="{% url 'companions:first_companion' %}"><img height="250" width="250" src="{% static 'companions/img/abubakr.png' %}" alt="Abu Bakr" /></a>
        </div>
        <div class="col">
          <a href="{% url 'companions:second_companion' %}"><img  height="250" width="250"src="{% static 'companions/img/Umar.png' %}" alt="Umar" /></a>
        </div>
        <div class="col">
          <a href="{% url 'companions:third_companion' %}"><img height="250" width="250" src="{% static 'companions/img/uthman.png' %}" alt="Uthman" /></a>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <a href="{% url 'companions:fourth_companion' %}"><img  height="250" width="250"src="{% static 'companions/img/Ali.png' %}" alt="Ali" /></a>
        </div>
        <div class="col">
          <a href="{% url 'companions:fifth_companion' %}"><img  height="250" width="250" src="{% static 'companions/img/talhah.png' %}" alt="Talhah" /></a>
        </div>
        <div class="col">
          <a href="{% url 'companions:sixth_companion' %}"><img  height="250" width="250" src="{% static 'companions/img/Zubayr.png' %}" alt="Zubayr" /></a>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <a href="{% url 'companions:seventh_companion' %}"><img  height="250" width="250" src="{% static 'companions/img/AbdurRahman.png' %}" alt="Abdu-Rahman bin Awf" /></a>
        </div>
        <div class="col">
          <a href="{% url 'companions:eighth_companion' %}"><img  height="250" width="250" src="{% static 'companions/img/Saad.png' %}" alt="Sa'ad bin Abi Waqqas" /></a>
        </div>
        <div class="col">
          <a href="{% url 'companions:ninth_companion' %}"><img  height="250" width="250" src="{% static 'companions/img/Said.png' %}" alt="Sa'id bin Zayd" /></a>
        </div>
      </div>
      <div class="row">
        <div clas="col">
          <a href="{% url 'companions:tenth_companion' %}"><img  height="250" width="250" src="{% static 'companions/img/AbuUbaidah.png' %}" alt="Abu Ubaidah bin Al-Jarrah" /></a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

companions/templates/companions/top6.html
{% extends 'companions/base.html' %}
{% block body_block %}
{% load staticfiles %}
<div class="container">
  <div class="jumbotron">
    <h4> Here are the top 6 things you need to do to get to the highest in Paradise </h4>
    <audio>
      <source src="{% static 'companions/audio/paradise.mp3' %}" type="audio/mpeg">
    </audio>
  </div>
</div>
{% endblock %}